lesson6. first try
denio-rus/TestGuru pull request #5
Opened 2018-08-09 17:22 UTC by denio-rus

scopes & validations

2018-08-10 09:09 UTC, iBublik requested changes

2018-08-10 09:09 UTC, iBublik commented on app/models/answer.rb
> +  validate :max_number_of_aswers
Эта валидация сейчас не даст обновить ответ, если у вопроса создано 4 ответа. Нужно вызывать ее только при создании ответа

2018-08-10 09:09 UTC, iBublik commented on app/models/answer.rb
> +    if Answer.where(question_id: question_id).size == 4
Используй `question.answers.count`. size может вести себя нестабильно - если ассоциации загружены в память, он просто возвращает длину массива. Т.е. ответ может быть как раз 4м по счету, а из-за size ты не сможешь его сохранить.
https://stackoverflow.com/a/12257642

2018-08-10 09:09 UTC, iBublik commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
`default_scope` меняет поведение всех запросов к таблице, поэтому его стоит держать на виду - в самом верху класса

2018-08-10 09:09 UTC, iBublik commented on app/models/category.rb
> +  validates :title, presence: true
Ассоциации, валидации, скоупы - это логически разные блоки. Отделяй их пустой строкой

2018-08-10 09:09 UTC, iBublik commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
0 - не положительное число

2018-08-10 09:09 UTC, iBublik commented on app/models/user.rb
> +  scope :tests_by_level, -> { tests.where(level: level) }
Скоуп нерабочий:
1. Ассоциации работают только на уровне инстанса. Сам посмотри - если вызвать `User.tests_by_level`, какие именно тесты должны выбираться?
2. Не определена переменная level
В общем оставь как было

2018-08-10 09:09 UTC, iBublik commented on db/migrate/20180809160932_add_unique_index_to_tests.rb
> +    add_index :tests, [:title, :level], unique: true
Если поменяь порядок полей в этом индексе, то поиск тестов по уровню сможет использовать его, что ускорит работу методов

2018-08-10 14:21 UTC, denio-rus commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
Тут не понял. only_integer - это же все целые числа и ноль. Тесты с 0 уровнем сохраняются.

2018-08-11 08:47 UTC, iBublik approved these changes

2018-08-11 08:47 UTC, iBublik commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
По заданию уровень может быть только положительным целым числом

2018-08-12 01:59 UTC, merged